In [1]:
import pandas as pd

# Load CSV files
csv_file1_path = 'Electric_Vehicle_Population_Data.csv'  # Replace with the actual path
csv_file2_path = 'us_cities.csv'  # Replace with the actual path

df_csv1 = pd.read_csv(csv_file1_path)

df_csv2 = pd.read_csv(csv_file2_path)

# Load Excel file
excel_file_path = 'median_household_income_estimates.xlsx'  # Replace with the actual path
df_excel = pd.read_excel(excel_file_path,header=3)

# Explore the datasets
print("CSV File 1:")
print(df_csv1.head())
print(df_csv1.info())
print(df_csv1.describe())

CSV File 1:
   VIN (1-10)    County      City State  Postal Code  Model Year     Make  \
0  KM8K33AGXL      King   Seattle    WA      98103.0        2020  HYUNDAI
1  1C4RJYB61N      King   Bothell    WA      98011.0        2022     JEEP
2  1C4RJYD61P    Yakima    Yakima    WA      98908.0        2023     JEEP
3  5YJ3E1EA7J      King  Kirkland    WA      98034.0        2018    TESLA
4  WBY7Z8C5XJ  Thurston   Olympia    WA      98501.0        2018      BMW

            Model                   Electric Vehicle Type  \
0            KONA          Battery Electric Vehicle (BEV)
1  GRAND CHEROKEE  Plug-in Hybrid Electric Vehicle (PHEV)
2  GRAND CHEROKEE  Plug-in Hybrid Electric Vehicle (PHEV)
3         MODEL 3          Battery Electric Vehicle (BEV)
4              I3  Plug-in Hybrid Electric Vehicle (PHEV)

  Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0           Clean Alternative Fuel Vehicle Eligible             258
1             Not eligible due to low battery range              25
2             Not eligible due to low battery range              25
3           Clean Alternative Fuel Vehicle Eligible             215
4           Clean Alternative Fuel Vehicle Eligible              97

   Base MSRP  Legislative District  DOL Vehicle ID  \
0          0                  43.0       249675142
1          0                   1.0       233928502
2          0                  14.0       229675939
3          0                  45.0       104714466
4          0                  22.0       185498386

                  Vehicle Location  \
0     POINT (-122.34301 47.659185)
1     POINT (-122.20578 47.762405)
2  POINT (-120.6027202 46.5965625)
3     POINT (-122.209285 47.71124)
4     POINT (-122.89692 47.043535)

                                Electric Utility  2020 Census Tract
0   CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303300e+10
1  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303302e+10
2                                     PACIFICORP       5.307700e+10
3  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303302e+10
4                         PUGET SOUND ENERGY INC       5.306701e+10
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150482 entries, 0 to 150481
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         150482 non-null  object
 1   County                                             150479 non-null  object
 2   City                                               150479 non-null  object
 3   State                                              150482 non-null  object
 4   Postal Code                                        150479 non-null  float64
 5   Model Year                                         150482 non-null  int64
 6   Make                                               150482 non-null  object
 7   Model                                              150482 non-null  object
 8   Electric Vehicle Type                              150482 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  150482 non-null  object
 10  Electric Range                                     150482 non-null  int64
 11  Base MSRP                                          150482 non-null  int64
 12  Legislative District                               150141 non-null  float64
 13  DOL Vehicle ID                                     150482 non-null  int64
 14  Vehicle Location                                   150475 non-null  object
 15  Electric Utility                                   150479 non-null  object
 16  2020 Census Tract                                  150479 non-null  float64
dtypes: float64(3), int64(4), object(10)
memory usage: 19.5+ MB
None
         Postal Code     Model Year  Electric Range      Base MSRP  \
count  150479.000000  150482.000000   150482.000000  150482.000000
mean    98168.344154    2020.005436       67.877839    1312.644735
std      2473.612184       3.015209       96.230009    9231.310215
min      1730.000000    1997.000000        0.000000       0.000000
25%     98052.000000    2018.000000        0.000000       0.000000
50%     98122.000000    2021.000000       18.000000       0.000000
75%     98370.000000    2023.000000       97.000000       0.000000
max     99577.000000    2024.000000      337.000000  845000.000000

       Legislative District  DOL Vehicle ID  2020 Census Tract
count         150141.000000    1.504820e+05       1.504790e+05
mean              29.343950    2.111122e+08       5.297195e+10
std               14.824829    8.196388e+07       1.638841e+09
min                1.000000    4.385000e+03       1.081042e+09
25%               18.000000    1.693473e+08       5.303301e+10
50%               33.000000    2.150306e+08       5.303303e+10
75%               43.000000    2.399119e+08       5.305307e+10
max               49.000000    4.792548e+08       5.603300e+10

In [5]:
print("\nCSV File 2:")
print(df_csv2.head())
print(df_csv2.info())
print(df_csv2.describe())

CSV File 2:
   Unnamed: 0         City       State     Region   Size  Population  AvgRent  \
0           0     New York    New York  Northeast  Large  20140470.0     3272
1           1  Los Angeles  California       West  Large  13200998.0     2857
2           2      Chicago    Illinois    Midwest  Large   9618502.0     1975
3           3       Dallas       Texas      South  Large   7637387.0     1754
4           4      Houston       Texas      South  Large   7122240.0     1620

   MedianRent  UnempRate  AvgIncome  CostOfLiving  PriceParity  CommuteTime  \
0      2323.0        3.8    85136.0         128.0       114.58         36.7
1      1925.0        3.9    75821.0         140.6       113.82         30.7
2      1364.0        4.2    71992.0         100.1       105.42         31.8
3      1440.0        3.2    66727.0          98.5       103.85         28.6
4      1216.0        3.9    64837.0          95.8        99.74         30.0

   MedianAQI  WalkScore  BikeScore  TransitScore  Latitude  Longitude
0       50.0       88.0       69.3           6.9   40.6943   -73.9249
1       70.0       68.6       58.7           6.2   34.1141  -118.4068
2       50.0       77.2       72.2           5.1   41.8375   -87.6866
3       51.0       46.0       49.3           2.8   32.7935   -96.7667
4       57.0       47.5       48.6           2.8   29.7860   -95.3885
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    344 non-null    int64
 1   City          344 non-null    object
 2   State         344 non-null    object
 3   Region        344 non-null    object
 4   Size          344 non-null    object
 5   Population    344 non-null    float64
 6   AvgRent       344 non-null    int64
 7   MedianRent    338 non-null    float64
 8   UnempRate     335 non-null    float64
 9   AvgIncome     344 non-null    float64
 10  CostOfLiving  335 non-null    float64
 11  PriceParity   343 non-null    float64
 12  CommuteTime   289 non-null    float64
 13  MedianAQI     302 non-null    float64
 14  WalkScore     74 non-null     float64
 15  BikeScore     74 non-null     float64
 16  TransitScore  344 non-null    float64
 17  Latitude      344 non-null    float64
 18  Longitude     344 non-null    float64
dtypes: float64(13), int64(2), object(4)
memory usage: 51.2+ KB
None
       Unnamed: 0    Population      AvgRent   MedianRent   UnempRate  \
count  344.000000  3.440000e+02   344.000000   338.000000  335.000000
mean   171.500000  8.091447e+05  1493.375000  1044.568047    3.325373
std     99.448479  1.752598e+06   499.698727   352.917181    1.279893
min      0.000000  5.863900e+04   657.000000   648.000000    1.600000
25%     85.750000  1.556702e+05  1160.250000   821.000000    2.500000
50%    171.500000  2.766250e+05  1393.000000   947.500000    3.100000
75%    257.250000  6.694870e+05  1736.250000  1165.000000    3.800000
max    343.000000  2.014047e+07  3422.000000  3000.000000   13.700000

           AvgIncome  CostOfLiving  PriceParity  CommuteTime   MedianAQI  \
count     344.000000    335.000000   343.000000   289.000000  302.000000
mean    57241.354651     97.086866    95.097201    23.273702   41.016556
std     12594.193756     13.083548     6.180207     3.837995    8.868721
min     34503.000000     82.600000    85.480000    15.700000   10.000000
25%     49462.000000     88.700000    90.620000    20.600000   38.000000
50%     54586.500000     93.100000    93.660000    22.800000   42.000000
75%     61529.000000    101.400000    98.235000    25.100000   44.000000
max    136338.000000    178.600000   119.830000    39.400000   84.000000

       WalkScore  BikeScore  TransitScore    Latitude   Longitude
count  74.000000  74.000000    344.000000  344.000000  344.000000
mean   48.402703  51.610811      2.191860   37.974277  -92.980435
std    15.904699  12.466191      1.431178    5.539083   15.822677
min    21.400000  29.700000      0.000000   21.329400 -157.846000
25%    36.825000  42.025000      1.175000   34.095025 -100.530150
50%    44.550000  50.900000      2.000000   38.506700  -87.978500
75%    60.025000  59.600000      3.000000   41.780325  -81.510075
max    88.700000  83.500000      6.900000   64.835300  -68.790600

In [6]:
print("\nExcel File:")
print(county_dropna.head())
print(county_dropna.info())
print(county_dropna.describe())

Excel File:
   Unnamed: 0   1989       1990       1991       1992       1993       1994  \
1  Washington  31183  33417.061  34379.118  35881.524  36678.568  37894.965
2       Adams  24604  28024.074  27300.700  28328.127  31277.360  29537.150
3      Asotin  22897  24206.219  25110.440  26250.554  27358.886  27872.895
4      Benton  32593  35011.606  37093.354  39227.763  41153.190  42789.890
5      Chelan  24312  25833.442  27592.308  28745.697  30148.302  31546.570

        1995       1996       1997  ...          2013          2014      2015  \
1  38996.782  40568.226  42399.362  ...  57283.938988  60153.000000  63439.20
2  29603.720  31806.107  31794.792  ...  43541.081153  45711.821556  47645.73
3  28288.256  29812.595  31498.836  ...  42173.781687  43367.862197  46107.27
4  42539.628  42816.605  44056.502  ...  63709.962074  63157.401995  62071.02
5  32163.776  33918.164  35661.808  ...  51712.871368  50825.030213  53067.96

           2016          2017          2018     2019     2020     2021  \
1  65500.290875  69287.868831  72297.030172  78674.0  80319.0  84155.0
2  49501.385091  48848.793830  52870.057114  53535.0  56421.0  57405.0
3  47020.113312  51766.880459  50746.366302  54776.0  53377.0  56438.0
4  62282.049221  63501.707462  67912.297802  72847.0  75882.0  77339.0
5  55109.142422  60790.913046  60747.403036  59838.0  61546.0  64700.0

           2022
1  86343.030000
2  58406.161270
3  59674.538547
4  78823.975660
5  68015.630585

[5 rows x 35 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 40 entries, 1 to 40
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  40 non-null     object
 1   1989        40 non-null     object
 2   1990        40 non-null     float64
 3   1991        40 non-null     float64
 4   1992        40 non-null     float64
 5   1993        40 non-null     float64
 6   1994        40 non-null     float64
 7   1995        40 non-null     float64
 8   1996        40 non-null     float64
 9   1997        40 non-null     float64
 10  1998        40 non-null     float64
 11  1999        40 non-null     float64
 12  2000        40 non-null     float64
 13  2001        40 non-null     float64
 14  2002        40 non-null     float64
 15  2003        40 non-null     float64
 16  2004        40 non-null     float64
 17  2005        40 non-null     float64
 18  2006        40 non-null     float64
 19  2007        40 non-null     float64
 20  2008        40 non-null     float64
 21  2009        40 non-null     float64
 22  2010        40 non-null     float64
 23  2011        40 non-null     float64
 24  2012        40 non-null     float64
 25  2013        40 non-null     float64
 26  2014        40 non-null     float64
 27  2015        40 non-null     float64
 28  2016        40 non-null     float64
 29  2017        40 non-null     float64
 30  2018        40 non-null     float64
 31  2019        40 non-null     float64
 32  2020        40 non-null     float64
 33  2021        40 non-null     float64
 34  2022        40 non-null     float64
dtypes: float64(33), object(2)
memory usage: 11.2+ KB
None
               1990          1991          1992          1993          1994  \
count     40.000000     40.000000     40.000000     40.000000     40.000000
mean   28223.700825  28954.065350  30205.607650  31392.007450  32175.768375
std     4575.680605   4753.056847   4889.532185   4807.707184   5177.852744
min    20580.170000  21596.128000  22449.189000  23371.940000  24298.750000
25%    25260.340750  25765.361000  27062.768500  28111.836000  28890.730000
50%    27333.008000  27726.710000  28712.867500  30425.219000  30952.147500
75%    31164.431750  31972.133500  32733.970750  33367.013500  34560.516250
max    38819.799000  39867.516000  41670.233000  42417.842000  43809.560000

               1995          1996          1997          1998          1999  \
count     40.000000     40.000000     40.000000     40.000000     40.000000
mean   33080.104300  34958.697875  36350.224250  37903.933975  38516.825000
std     5111.451717   5063.770241   5539.372182   5848.046451   6232.585646
min    25494.906000  27425.108000  28046.638000  29173.679000  28584.000000
25%    29738.246500  31715.037250  32274.886500  34017.292750  34092.000000
50%    32003.760000  33965.914000  35290.763000  36505.844000  37312.000000
75%    35753.011500  37425.297500  39120.347000  41249.995250  42658.500000
max    45397.216000  47415.568000  50679.670000  52341.735000  53157.000000

       ...          2013          2014          2015          2016  \
count  ...     40.000000     40.000000     40.000000     40.000000
mean   ...  49105.810008  50761.607587  52249.056750  53799.043726
std    ...   8479.501773   8890.277653   9296.307262   9640.876519
min    ...  35934.080179  35145.684393  39806.910000  41027.860274
25%    ...  43127.710757  43288.330816  46376.797500  47674.561281
50%    ...  46956.731129  50258.359429  49947.480000  51704.345731
75%    ...  56069.433413  58074.032132  58062.757500  59401.202942
max    ...  71121.833329  75044.587034  80997.840000  84896.903375

               2017          2018           2019           2020          2021  \
count     40.000000     40.000000      40.000000      40.000000      40.00000
mean   56172.150960  58688.770143   63475.400000   65179.150000   68643.10000
std    10595.579958  11385.965350   11918.262403   12337.837261   12836.10536
min    42275.928582  42211.700231   44777.000000   47722.000000   50565.00000
25%    47607.978261  50681.978518   56172.000000   55953.000000   60149.50000
50%    54732.403964  57341.428716   60379.000000   61822.500000   64696.00000
75%    60910.150509  64338.624605   69125.500000   74870.250000   75550.75000
max    88466.433390  93707.080585  102338.000000  102620.000000  110351.00000

                2022
count      40.000000
mean    71369.734809
std     14150.231010
min     52988.946375
25%     62709.392152
50%     67443.170307
75%     78158.272941
max    118664.424099

[8 rows x 33 columns]

In [4]:
county_dropna=df_excel.dropna()

county_dropna

,Unnamed: 0,1989,1990,1991,1992,1993,1994,1995,1996,1997,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,Washington,31183,33417.061,34379.118,35881.524,36678.568,37894.965,38996.782,40568.226,42399.362,...,57283.938988,60153.000000,63439.20,65500.290875,69287.868831,72297.030172,78674.0,80319.0,84155.0,86343.030000
2,Adams,24604,28024.074,27300.700,28328.127,31277.360,29537.150,29603.720,31806.107,31794.792,...,43541.081153,45711.821556,47645.73,49501.385091,48848.793830,52870.057114,53535.0,56421.0,57405.0,58406.161270
3,Asotin,22897,24206.219,25110.440,26250.554,27358.886,27872.895,28288.256,29812.595,31498.836,...,42173.781687,43367.862197,46107.27,47020.113312,51766.880459,50746.366302,54776.0,53377.0,56438.0,59674.538547
4,Benton,32593,35011.606,37093.354,39227.763,41153.190,42789.890,42539.628,42816.605,44056.502,...,63709.962074,63157.401995,62071.02,62282.049221,63501.707462,67912.297802,72847.0,75882.0,77339.0,78823.975660
5,Chelan,24312,25833.442,27592.308,28745.697,30148.302,31546.570,32163.776,33918.164,35661.808,...,51712.871368,50825.030213,53067.96,55109.142422,60790.913046,60747.403036,59838.0,61546.0,64700.0,68015.630585
6,Clallam,25434,27329.220,27861.112,28577.986,29340.212,29950.640,31162.518,32558.772,34769.840,...,44823.809823,45453.815015,46240.92,48187.110514,47766.585450,55664.085098,57571.0,54712.0,62623.0,65652.257946
7,Clark,31800,33734.144,34249.606,35847.176,37418.128,38827.825,40524.724,43043.660,45704.738,...,57852.097282,61710.835969,63639.18,66782.167466,71922.312535,71658.814710,80407.0,76929.0,83790.0,87397.382557
8,Columbia,22418,24477.666,24122.504,26136.154,28122.932,26778.530,29860.742,33040.962,30820.402,...,39930.873238,42886.165354,39806.91,41516.903351,43621.614616,46549.833172,56338.0,58220.0,59650.0,61115.123669
9,Cowlitz,27866,29745.963,31037.618,31194.645,31956.738,33309.395,34191.416,35515.572,36738.208,...,43409.101256,39635.098026,49996.98,48207.638073,47132.156694,54587.896438,57316.0,64357.0,70104.0,76364.199947
10,Douglas,27054,28707.820,29406.714,30931.719,31854.602,32688.475,32929.620,35420.349,36854.928,...,49029.710347,50877.786176,50886.00,52363.805164,54580.839254,65913.013502,63086.0,64768.0,64932.0,65096.415267
11,Ferry,25170,27354.947,27236.322,27840.506,27828.962,29586.795,28910.246,30091.384,30489.114,...,39596.347076,41343.457580,40339.53,42329.569217,45546.453756,42211.700231,47463.0,47722.0,50565.0,53577.369452
12,Franklin,24604,26435.236,26861.080,28680.038,30902.036,31767.855,32604.236,34842.933,35770.496,...,56105.085439,58537.866647,57663.54,58854.231340,63345.303260,62516.341309,63575.0,73656.0,79532.0,85876.765287
13,Garfield,25156,26533.853,27185.086,28554.181,30368.416,27043.815,30434.924,34958.555,34791.784,...,44445.941705,44683.785317,46616.13,46358.408921,47036.972743,44807.533448,54555.0,56804.0,61268.0,66082.807971
14,Grant,22372,24216.100,25463.222,26996.038,29172.448,29978.170,30383.740,32737.726,33977.242,...,46035.622249,50355.865275,50067.27,52980.588676,60344.260102,58052.979669,57152.0,54753.0,61815.0,65593.244374
15,Grays Harbor,23042,24052.501,24676.778,26037.850,27002.136,27252.180,28638.116,29792.047,31368.316,...,40322.738961,41687.060296,43901.55,44627.460088,44080.377970,45139.366029,59346.0,54034.0,55018.0,56019.919384
16,Island,29161,30642.372,32030.230,33139.450,34594.072,35974.585,37178.064,39716.226,41901.474,...,52014.094746,57919.420627,59961.33,61690.835137,60785.685388,63137.543826,72173.0,76965.0,76729.0,76493.723654
17,Jefferson,25197,27293.503,28464.900,29171.341,29884.880,30605.910,31058.324,32530.314,34282.464,...,46957.149432,50160.853584,52886.79,54864.427496,54883.968674,57485.002269,60556.0,66386.0,61548.0,63640.632000
18,King,36179,38632.719,39830.512,41646.559,42234.320,43809.560,45397.216,46725.847,48270.720,...,71121.833329,75044.587034,80997.84,84896.903375,88466.433390,93707.080585,102338.0,102620.0,110351.0,118664.424099
19,Kitsap,32043,36144.876,37379.612,38403.536,39391.444,40407.190,40629.790,41739.690,44098.070,...,60199.792999,59604.689792,65155.86,66569.354796,70531.193525,74150.041081,79268.0,76814.0,86826.0,91736.704908
20,Kittitas,20489,21772.656,22793.416,23827.723,25125.782,26060.675,27088.868,28625.639,29774.578,...,46689.734988,47519.125251,46904.22,49275.476092,55123.823115,54372.130175,59172.0,64727.0,62721.0,60777.169357
21,Klickitat,23012,24590.047,24541.820,25517.916,27208.970,28739.005,29745.180,32935.313,33543.350,...,46733.463582,48085.966656,49542.57,51314.381113,55961.839709,57197.855162,60567.0,57476.0,61542.0,65895.639293
22,Lewis,24410,25975.050,26294.580,27552.234,28502.048,29743.535,30620.924,32111.908,33609.576,...,39609.309273,42406.162617,47142.81,47892.710604,50899.787877,57945.433953,58525.0,54578.0,63828.0,67909.762303
23,Lincoln,24617,26615.648,26590.766,28191.563,29776.898,28941.305,31843.744,35151.668,35837.886,...,46956.312826,48975.939184,49276.26,51019.020628,50657.344758,50488.815165,60849.0,61332.0,64692.0,68236.073567
24,Mason,26304,27833.545,28585.020,29784.525,30775.850,31552.675,32791.674,34747.720,36523.502,...,47141.509205,52598.084098,53633.25,55824.000602,58228.036565,61623.525741,63689.0,63785.0,73696.0,77936.372035
25,Okanogan,20303,20580.170,22203.428,23696.784,25073.736,25998.610,25494.906,27576.485,28046.638,...,36291.719097,35145.684393,41425.56,41027.860274,44069.109658,47536.114292,44777.0,48979.0,55233.0,57422.270421
26,Pacific,20029,20977.170,21596.128,22449.189,23371.940,24298.750,25748.150,27425.108,28973.650,...,35934.080179,40449.114873,40677.12,42117.530049,44418.149393,45236.732782,50521.0,53319.0,58715.0,60936.117992
27,Pend Oreille,20808,22660.346,23213.508,24690.354,26102.686,27122.870,28327.732,29785.265,31223.262,...,42043.296252,39885.956756,41110.74,42390.813553,42275.928582,43299.449231,51950.0,57212.0,55060.0,52988.946375
28,Pierce,30412,33380.392,33975.580,35416.789,36209.616,37105.445,38222.132,39877.809,42596.136,...,57238.424679,59998.075901,59566.32,61042.117751,65517.388076,71207.578024,78779.0,80236.0,85492.0,91092.303505
29,San Juan,31278,32387.972,33298.078,34893.357,36059.060,38412.405,37596.318,39037.181,41134.112,...,60872.193212,58781.782780,59260.41,61391.349468,61267.862895,64057.630377,69113.0,74533.0,71678.0,68932.361290
30,Skagit,28389,30181.344,30979.332,31970.258,32842.838,34089.160,35277.994,36888.003,38449.092,...,56057.549404,54851.551673,56322.09,55524.018148,60175.057225,65181.607288,67551.0,78798.0,72831.0,67315.852699
31,Skamania,28778,31367.987,30999.712,31832.783,32282.524,33400.640,33364.364,36618.890,37409.148,...,51715.662496,51428.608202,53195.67,52700.130989,56323.843448,60767.306340,69163.0,68501.0,75158.0,82461.934337
32,Snohomish,36847,38819.799,39867.516,41670.233,42417.842,43740.515,44993.578,47415.568,50679.670,...,64391.320554,68637.101473,75292.47,77985.248791,81779.216953,86434.593529,89119.0,93589.0,99650.0,106103.521781
33,Spokane,25769,27336.796,28354.896,29569.891,30482.022,31630.800,32256.216,33517.006,34919.718,...,48311.561381,50856.252573,48189.24,49481.682628,49953.755809,55534.502136,59976.0,60827.0,65571.0,70684.992536
34,Stevens,24440,25608.720,26482.058,27518.704,28818.246,29854.325,29782.976,30758.970,32434.918,...,45528.427185,45682.707831,42416.55,44467.071039,45189.076968,44363.060581,55000.0,50958.0,60180.0,63240.814980
35,Thurston,30976,33139.333,34851.224,36676.182,37765.654,38939.170,39970.694,41496.886,43748.374,...,63407.502470,65288.220014,61676.01,63286.383133,68764.831073,69757.233707,77890.0,79769.0,81544.0,83358.496860
36,Wahkiakum,26969,28590.282,28458.606,29654.613,31076.380,31298.385,32687.996,34013.664,36566.314,...,43140.079973,47174.032028,49897.98,50872.387354,50432.812056,52309.460443,61123.0,62099.0,64777.0,67570.487914
37,Walla Walla,24414,25808.270,26242.192,27647.473,28901.774,30151.600,31014.370,32956.859,34094.440,...,47237.968102,50834.845398,49618.80,52094.310350,52721.214902,55720.637301,60202.0,61281.0,63631.0,66071.117655
38,Whatcom,28367,31096.580,31952.768,32598.811,32957.994,34030.510,34892.746,36492.240,37552.886,...,50879.469672,53481.221148,54522.27,55709.876627,60028.090455,61243.879132,68656.0,70463.0,71739.0,73038.106822
39,Whitman,21674,22948.832,23734.696,24389.068,25162.258,25134.400,26270.326,27838.171,28696.518,...,43090.603107,42217.731305,43378.83,49945.728429,52542.864192,53099.727535,45906.0,52066.0,53140.0,54236.154112
40,Yakima,23612,25483.772,25866.074,27085.012,28078.548,29163.560,29717.446,31441.828,32946.106,...,40696.379546,43049.736673,46422.09,46957.266880,46315.683722,50019.147050,55674.0,56353.0,60058.0,64006.589960